[package]
name = "oceaniam-common"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
config.workspace = true
garde.workspace = true
im.workspace = true
jsonwebtoken.workspace = true
log.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
rsa.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio.workspace = true
ts-rs.workspace = true
utoipa.workspace = true
uuid.workspace = true

migration.workspace = true

[dev-dependencies]
tokio.workspace = true
