[package]
name = "oceaniam-common"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
config.workspace = true
jsonwebtoken.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ts-rs.workspace = true
utoipa.workspace = true
uuid.workspace = true
