// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdministratorProfileVO = {
  id: string;
  name: string;
  role: string | null;
  permissions: Array<string>;
};
