// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sqid } from "./Sqid";

export type ApplicationUserVO = {
  id: Sqid;
  email: string | null;
  phone: string | null;
  nickname: string;
};
