// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationRoleVO = {
  id: string;
  application_id: string;
  name: string;
  is_system: boolean;
  permissions: Array<string>;
};
