// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Granularity } from "./Granularity";
import type { TrendDataPoint } from "./TrendDataPoint";

export type ApplicationTrendsVO = {
  granularity: Granularity;
  range: bigint;
  new_users: Array<TrendDataPoint>;
};
