// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationUserVO = {
  id: string;
  email: string | null;
  phone: string | null;
  nickname: string;
};
