// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationUsersSortOrder } from "./ApplicationUsersSortOrder";

export type ApplicationUsersListQuery = {
  page: bigint;
  per_page: bigint;
  sort_order: ApplicationUsersSortOrder;
};
