// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationKeyVO = {
  key_id: string;
  algorithm: string;
  status: string;
  created_at: string;
  activated_at: string;
  retired_at: string;
  expires_at: string;
  revoked_at: string | null;
};
