// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationConfigurationVO } from "./ApplicationConfigurationVO";

export type ApplicationDetailVO = {
  id: string;
  comment: string | null;
  tenant_id: string;
  configuration: ApplicationConfigurationVO;
};
