// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Argon2Configuration = {
  m_cost: number;
  t_cost: number;
  p_cost: number;
};
