// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sqid } from "./Sqid";
import type { JsonValue } from "./serde_json/JsonValue";

export type AuditLogVO = { id: Sqid; audit_type: string; payload: JsonValue; created_at: string };
