// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasswordConfigurationVO } from "./PasswordConfigurationVO";
import type { TokenConfigurationVO } from "./TokenConfigurationVO";

export type AuthConfigurationVO = {
  token: TokenConfigurationVO;
  password: PasswordConfigurationVO;
};
