// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sqid } from "./Sqid";

export type CreateApplicationResponse = {
  tenant_id: Sqid;
  application_id: Sqid;
  comment: string | null;
};
