// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateApplicationResponse = {
  tenant_id: string;
  application_id: string;
  comment: string | null;
};
