// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverviewVO = {
  total_tenants: bigint;
  total_applications: bigint;
  total_administrators: bigint;
  total_application_users: bigint;
  total_active_secrets: bigint;
};
