// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchAuthConfigurationVO } from "./PatchAuthConfigurationVO";
import type { PatchRegistrationConfigurationVO } from "./PatchRegistrationConfigurationVO";

export type PatchApplicationConfigurationRequest = {
  auth: PatchAuthConfigurationVO | null;
  registration: PatchRegistrationConfigurationVO | null;
};
