// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationUsersSortOrder } from "./ApplicationUsersSortOrder";
import type { Sqid } from "./Sqid";

export type SearchApplicationUsersQuery = {
  page: bigint;
  per_page: bigint;
  sort_order: ApplicationUsersSortOrder;
  by_nickname: string | null;
  by_email: string | null;
  by_phone: string | null;
  by_id: Sqid | null;
};
