// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SigninChallenge = { challenge_id: string; factor_type: string; expires_at: string };
