// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemClaim = {
  /**
   * Subject
   *
   * The subject of the token, typically the user's unique identifier (e.g., UUID)
   */
  sub: string;
  /**
   * Expiration Time
   *
   * Token expiration time (Unix timestamp, seconds)
   */
  exp: bigint;
  /**
   * Issued At
   *
   * Token issuance time (Unix timestamp, seconds)
   */
  iat: bigint;
  /**
   * Issuer
   *
   * Token issuer (optional), e.g., "oceaniam-auth"
   */
  iss: string | null;
  /**
   * Audience
   *
   * Token audience (optional), represents the intended recipient of the token
   */
  aud: Array<string> | null;
  /**
   * JWT ID
   *
   * Unique identifier for the token, used to prevent replay attacks
   */
  jti: string;
};
