// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCountByType } from "./ActivityCountByType";

export type TodayActivityVO = { total_events: bigint; by_type: Array<ActivityCountByType> };
