[package]
name = "oceaniam"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
backon.workspace = true
chrono.workspace = true
config.workspace = true
im.workspace = true
itertools.workspace = true
jsonwebtoken.workspace = true
log.workspace = true
mimalloc.workspace = true
moka.workspace = true
parking_lot.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tap.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
utoipa-axum.workspace = true
utoipa-scalar.workspace = true
utoipa.workspace = true
uuid.workspace = true

migration.workspace = true
oceaniam-common.workspace = true
oceaniam-credential.workspace = true
oceaniam-database.workspace = true
oceaniam-vo.workspace = true
oceaniam-keybox.workspace = true
