version: "3.8"
services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
      target: database
      labels:
        - docker.io/krysztal112233/oceaniam-database:latest
    restart: unless-stopped
    command: -c 'max_connections=20480'
    volumes:
      - postgres:/var/lib/postgresql/18/docker
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend-migration:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migration
      labels:
        - docker.io/krysztal112233/oceaniam-migration:latest
    restart: "no"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
      labels:
        - docker.io/krysztal112233/oceaniam-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      backend-migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: frontend
      labels:
        - docker.io/krysztal112233/oceaniam-frontend:latest
    restart: unless-stopped
    ports:
      - 8900:80
volumes:
  postgres:
