version: "3.8"

services:
  postgres:
    image: docker.io/krysztal112233/oceaniam-database:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: database
    restart: unless-stopped
    command: -c 'max_connections=20480' -c 'shared_preload_libraries=pg_duckdb'
    volumes:
      - postgres:/var/lib/postgresql/18/docker
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-migration:
    image: docker.io/krysztal112233/oceaniam-migration:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: migration
    restart: "no"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    image: docker.io/krysztal112233/oceaniam-backend:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      backend-migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  frontend:
    image: docker.io/krysztal112233/oceaniam-frontend:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: frontend
    restart: unless-stopped

  nginx:
    image: docker.io/krysztal112233/oceaniam-nginx:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    ports:
      - 8900:80
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started

volumes:
  postgres:
