[package]
name = "oceaniam-auth"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
im.workspace = true
jsonwebtoken.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true
utoipa.workspace = true
uuid.workspace = true

oceaniam-common.workspace = true
