[workspace]
members = [
	"crates/migration",
	"crates/oceaniam",
	"crates/oceaniam-api",
	"crates/oceaniam-audit",
	"crates/oceaniam-auth",
	"crates/oceaniam-common",
	"crates/oceaniam-credential",
	"crates/oceaniam-database",
	"crates/oceaniam-export",
	"crates/oceaniam-keybox",
	"crates/oceaniam-worker",
	"crates/oceaniam-vo",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
argon2 = { version = "0.5", features = ["std"] }
async-trait = "0.1"
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.12", features = ["typed-header", "query"] }
backon = "1.6"
bloomfilter = "3"
chacha20poly1305 = "0.10"
chrono = "0.4"
clap = { version = "*", features = ["derive"] }
config = { version = "0.15", default-features = false, features = ["toml"] }
cron = "0.15"
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
dotenvy = "0.15"
futures = "0.3"
garde = { version = "*", features = ["derive", "phone-number", "email"] }
im = { version = "15.1", features = ["serde"] }
itertools = "0.14"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
linkme = "0.3"
log = "0.4"
mimalloc = { version = "0.1", features = ["v3"] }
moka = { version = "0.12", features = ["future"] }
names = { version = "0.14", default-features = false }
num_cpus = "1.17"
parking_lot = "0.12"
rand = "0.8"
rapidhash = "4.4"
rayon = "1.11"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqids = "0.4"
strum = { version = "0.28", features = ["derive"] }
tap = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }

tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = { version = "2.5", features = ["serde"] }
utoipa = { version = "*", features = ["chrono", "url", "uuid", "axum_extras"] }
utoipa-axum = "*"
utoipa-scalar = { version = "*", features = ["axum"] }
uuid = { version = "1.18", features = ["v7"] }
xorf = "0.12"
yew = { version = "0.22", features = ["csr"] }
zeroize = "1.8"

# lock the fuck version. sucks.
rsa = { version = "0.9.8", features = ["serde", "pem"] }
crypto-common = "0.1.7"

migration = { path = "./crates/migration/" }
oceaniam-api = { path = "./crates/oceaniam-api/" }
oceaniam-audit = { path = "./crates/oceaniam-audit/" }
oceaniam-auth = { path = "./crates/oceaniam-auth/" }
oceaniam-common = { path = "./crates/oceaniam-common/" }
oceaniam-credential = { path = "./crates/oceaniam-credential/" }
oceaniam-database = { path = "./crates/oceaniam-database/" }
oceaniam-export = { path = "./crates/oceaniam-export/" }
oceaniam-keybox = { path = "./crates/oceaniam-keybox/" }
oceaniam = { path = "./crates/oceaniam/" }
oceaniam-worker = { path = "./crates/oceaniam-worker/" }
oceaniam-vo = { path = "./crates/oceaniam-vo/" }

[workspace.dependencies.totp-rs]
version = "5.7"
features = ["gen_secret", "otpauth", "qr", "serde_support"]

[workspace.dependencies.ts-rs]
version = "11.1"
features = ["uuid-impl", "serde-json-impl", "chrono-impl"]

[workspace.dependencies.sea-orm]
version = "1.1"
features = ["runtime-tokio", "sqlx-postgres"]

[workspace.dependencies.sea-orm-migration]
version = "1.1"
features = ["runtime-tokio", "sqlx-postgres"]

[workspace.dependencies.axum-valid]
default-features = false
features = ["basic", "garde"]
version = "0.24"
