<!-- NOTE: THIS FILE GENERATED BY AI -->
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, shallowRef, watch } from "vue";
import type * as Monaco from "monaco-editor";
import type { editor } from "monaco-editor";
import type { ApplicationConfigurationVO } from "../../packages/sdk/src/types/ApplicationConfigurationVO";

type MonacoRuntime = typeof Monaco;
type FormatterRuntime = {
    format(source: string, options?: object): Promise<string>;
};
type FormatterPlugin = object;
type MonacoEnvironment = {
    getWorker: (_workerId: string, label: string) => Worker | Promise<Worker>;
};
type SubmitHandler = (
    nextValue: ApplicationConfigurationVO,
    rawValue: string,
) => Promise<void> | void;

declare global {
    interface Window {
        MonacoEnvironment?: MonacoEnvironment;
    }
}

const props = withDefaults(
    defineProps<{
        value: ApplicationConfigurationVO | null;
        title?: string;
        description?: string;
        onSubmit?: SubmitHandler;
    }>(),
    {
        title: "Configuration",
        description: "查看当前完整配置 JSON",
        onSubmit: undefined,
    },
);

const containerRef = ref<HTMLDivElement | null>(null);
const formattedValue = ref("");
const formatError = ref<string | null>(null);
const validationError = ref<string | null>(null);
const submitError = ref<string | null>(null);
const loadingEditor = ref(false);
const loadError = ref<string | null>(null);
const submitting = ref(false);
const isEditing = ref(false);
const editorInstance = shallowRef<editor.IStandaloneCodeEditor | null>(null);
const modelRef = shallowRef<editor.ITextModel | null>(null);

let formatRunId = 0;
let editorBootRunId = 0;
let monacoEnvironmentConfigured = false;
let monacoModulePromise: Promise<MonacoRuntime> | null = null;
let formatterPromise: Promise<{
    prettier: FormatterRuntime;
    prettierPluginBabel: FormatterPlugin;
    prettierPluginEstree: FormatterPlugin;
}> | null = null;

const hasConfiguration = computed(() => props.value !== null);
const canEdit = computed(
    () => hasConfiguration.value && !loadingEditor.value && !loadError.value,
);
const submitDisabled = computed(
    () => submitting.value || loadingEditor.value || !!loadError.value,
);

function createFallbackJson(value: ApplicationConfigurationVO): string {
    return `${JSON.stringify(value, null, 4)}\n`;
}

async function loadFormatter() {
    if (!formatterPromise) {
        formatterPromise = Promise.all([
            import("prettier/standalone"),
            import("prettier/plugins/babel"),
            import("prettier/plugins/estree"),
        ]).then(([prettier, prettierPluginBabel, prettierPluginEstree]) => {
            const runtimePrettier = (
                "default" in prettier ? prettier.default : prettier
            ) as FormatterRuntime;
            const runtimeBabelPlugin = (
                "default" in prettierPluginBabel
                    ? prettierPluginBabel.default
                    : prettierPluginBabel
            ) as FormatterPlugin;
            const runtimeEstreePlugin = (
                "default" in prettierPluginEstree
                    ? prettierPluginEstree.default
                    : prettierPluginEstree
            ) as FormatterPlugin;

            return {
                prettier: runtimePrettier,
                prettierPluginBabel: runtimeBabelPlugin,
                prettierPluginEstree: runtimeEstreePlugin,
            };
        });
    }

    return formatterPromise;
}

async function loadMonaco(): Promise<MonacoRuntime> {
    if (!monacoModulePromise) {
        monacoModulePromise = import("monaco-editor");
    }

    return monacoModulePromise;
}

async function ensureMonacoEnvironment(): Promise<MonacoRuntime> {
    const monaco = await loadMonaco();

    if (monacoEnvironmentConfigured || typeof window === "undefined") {
        return monaco;
    }

    const [{ default: EditorWorker }, { default: JsonWorker }] =
        await Promise.all([
            import("monaco-editor/esm/vs/editor/editor.worker?worker"),
            import("monaco-editor/esm/vs/language/json/json.worker?worker"),
            import("monaco-editor/esm/vs/language/json/monaco.contribution.js"),
        ]);

    window.MonacoEnvironment = {
        getWorker(_workerId: string, label: string): Worker {
            if (label === "json") {
                return new JsonWorker();
            }

            return new EditorWorker();
        },
    };

    monacoEnvironmentConfigured = true;
    return monaco;
}

async function createOrReuseModel(
    monaco: MonacoRuntime,
    initialValue: string,
): Promise<editor.ITextModel> {
    const modelUri = monaco.Uri.parse(
        "inmemory://oceaniam/application-configuration.json",
    );
    const existingModel = monaco.editor.getModel(modelUri);
    if (existingModel) {
        existingModel.setValue(initialValue);
        return existingModel;
    }

    return monaco.editor.createModel(initialValue, "json", modelUri);
}

function setEditorReadonly(readonly: boolean): void {
    editorInstance.value?.updateOptions({
        readOnly: readonly,
        domReadOnly: readonly,
    });
}

async function ensureEditor(): Promise<void> {
    if (
        !containerRef.value ||
        editorInstance.value ||
        !hasConfiguration.value
    ) {
        return;
    }

    const currentBootRunId = editorBootRunId + 1;
    editorBootRunId = currentBootRunId;
    loadingEditor.value = true;
    loadError.value = null;

    try {
        const monaco = await ensureMonacoEnvironment();
        if (
            currentBootRunId !== editorBootRunId ||
            !containerRef.value ||
            editorInstance.value
        ) {
            return;
        }

        modelRef.value = await createOrReuseModel(monaco, formattedValue.value);
        editorInstance.value = monaco.editor.create(containerRef.value, {
            model: modelRef.value,
            automaticLayout: true,
            readOnly: !isEditing.value,
            domReadOnly: !isEditing.value,
            minimap: { enabled: false },
            scrollBeyondLastLine: false,
            wordWrap: "on",
            tabSize: 4,
            renderLineHighlight: "none",
            contextmenu: true,
            padding: {
                top: 16,
                bottom: 16,
            },
        });
    } catch (error) {
        if (currentBootRunId !== editorBootRunId) {
            return;
        }

        loadError.value =
            error instanceof Error ? error.message : "加载配置编辑器失败。";
    } finally {
        if (currentBootRunId === editorBootRunId) {
            loadingEditor.value = false;
        }
    }
}

function syncEditorValue(nextValue: string): void {
    const model = modelRef.value;
    if (!model) {
        return;
    }

    if (model.getValue() !== nextValue) {
        model.setValue(nextValue);
    }
}

async function formatConfiguration(
    value: ApplicationConfigurationVO | null,
): Promise<void> {
    const currentRunId = formatRunId + 1;
    formatRunId = currentRunId;

    if (!value) {
        formatError.value = null;
        formattedValue.value = "";
        syncEditorValue("");
        return;
    }

    const fallback = createFallbackJson(value);

    try {
        const { prettier, prettierPluginBabel, prettierPluginEstree } =
            await loadFormatter();
        const formatted = await prettier.format(JSON.stringify(value), {
            parser: "json-stringify",
            plugins: [prettierPluginBabel, prettierPluginEstree],
            tabWidth: 4,
        });

        if (currentRunId !== formatRunId) {
            return;
        }

        formatError.value = null;
        formattedValue.value = formatted;
        if (!isEditing.value) {
            syncEditorValue(formatted);
        }
    } catch {
        if (currentRunId !== formatRunId) {
            return;
        }

        formatError.value = "Prettier 格式化失败，已回退到基础 JSON 缩进展示。";
        formattedValue.value = fallback;
        if (!isEditing.value) {
            syncEditorValue(fallback);
        }
    }
}

function disposeEditor(): void {
    editorInstance.value?.dispose();
    editorInstance.value = null;
    modelRef.value?.dispose();
    modelRef.value = null;
}

function getEditorValue(): string {
    return modelRef.value?.getValue() ?? formattedValue.value;
}

function beginEdit(): void {
    if (!canEdit.value) {
        return;
    }

    validationError.value = null;
    submitError.value = null;
    isEditing.value = true;
    syncEditorValue(formattedValue.value);
    setEditorReadonly(false);
    editorInstance.value?.focus();
}

function cancelEdit(): void {
    validationError.value = null;
    submitError.value = null;
    isEditing.value = false;
    syncEditorValue(formattedValue.value);
    setEditorReadonly(true);
}

async function submitChanges(): Promise<void> {
    if (!isEditing.value || submitDisabled.value) {
        return;
    }

    validationError.value = null;
    submitError.value = null;

    const rawValue = getEditorValue();
    let parsedValue: ApplicationConfigurationVO;

    try {
        parsedValue = JSON.parse(rawValue) as ApplicationConfigurationVO;
    } catch (error) {
        validationError.value =
            error instanceof Error
                ? `JSON 解析失败: ${error.message}`
                : "JSON 解析失败。";
        return;
    }

    submitting.value = true;

    try {
        await props.onSubmit?.(parsedValue, rawValue);
        await formatConfiguration(parsedValue);
        isEditing.value = false;
        syncEditorValue(formattedValue.value);
        setEditorReadonly(true);
    } catch (error) {
        submitError.value =
            error instanceof Error ? error.message : "提交配置失败。";
    } finally {
        submitting.value = false;
    }
}

watch(
    () => props.value,
    (value) => {
        if (!value) {
            isEditing.value = false;
            validationError.value = null;
            submitError.value = null;
        }

        void formatConfiguration(value);
        if (value) {
            void ensureEditor();
        }
    },
    { immediate: true, deep: true },
);

watch(containerRef, () => {
    void ensureEditor();
});

watch(isEditing, (editing) => {
    setEditorReadonly(!editing);
});

watch(hasConfiguration, (available) => {
    if (available) {
        void ensureEditor();
        if (!isEditing.value) {
            syncEditorValue(formattedValue.value);
        }
        return;
    }

    disposeEditor();
    loadingEditor.value = false;
    loadError.value = null;
});

onBeforeUnmount(() => {
    disposeEditor();
});
</script>

<template>
    <section class="rounded-box border border-base-200 bg-base-100">
        <div class="flex flex-col gap-4 px-5 py-5">
            <div
                class="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"
            >
                <div class="space-y-1">
                    <h3 class="text-base font-medium text-base-content">
                        {{ title }}
                    </h3>
                    <p class="text-sm text-base-content/60">
                        {{ description }}
                    </p>
                </div>

                <div class="flex flex-wrap items-center gap-2">
                    <button
                        v-if="!isEditing"
                        type="button"
                        class="btn btn-outline btn-sm"
                        :disabled="!canEdit"
                        @click="beginEdit"
                    >
                        编辑
                    </button>

                    <template v-else>
                        <button
                            type="button"
                            class="btn btn-ghost btn-sm"
                            :disabled="submitting"
                            @click="cancelEdit"
                        >
                            取消
                        </button>

                        <button
                            type="button"
                            class="btn btn-primary btn-sm"
                            :disabled="submitDisabled"
                            @click="submitChanges"
                        >
                            {{ submitting ? "提交中..." : "提交" }}
                        </button>
                    </template>
                </div>
            </div>

            <div
                v-if="hasConfiguration"
                class="overflow-hidden rounded-box border border-base-200 bg-base-50"
            >
                <div ref="containerRef" class="h-105 w-full"></div>
            </div>

            <div
                v-else
                class="rounded-box border border-dashed border-base-300 bg-base-50 px-4 py-8 text-sm text-base-content/60"
            >
                暂无 configuration 数据。
            </div>
        </div>
    </section>
</template>
