[package]
name = "oceaniam-credential"
version.workspace = true
edition.workspace = true

[dependencies]
argon2.workspace = true
axum.workspace = true
log.workspace = true
sea-orm.workspace = true
serde.workspace = true
tap.workspace = true
thiserror.workspace = true
uuid.workspace = true

oceaniam-common.workspace = true
oceaniam-database.workspace = true
