[package]
name = "oceaniam-common"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum-extra = { workspace = true, features = ["cookie"] }
chrono.workspace = true
config.workspace = true
base64 = "0.22"
chacha20poly1305.workspace = true
crypto-common.workspace = true
hex = "0.4"
zeroize.workspace = true
garde.workspace = true
log.workspace = true
names.workspace = true
num_cpus.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
sqids.workspace = true
tap.workspace = true
tokio.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true

migration.workspace = true
