// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthVO = { email: string, password: string, } | { phone: string, password: string, };
