// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationConfigurationVO } from "./ApplicationConfigurationVO";
import type { Sqid } from "./Sqid";

export type ApplicationDetailVO = { id: Sqid, comment: string | null, tenant_id: Sqid, configuration: ApplicationConfigurationVO, };
