// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sqid } from "./Sqid";

export type ApplicationChallengeVO = {
    id: string;
    application_id: Sqid;
    subject_id: string;
    factor_type: string;
    purpose: string;
    status: string;
    attempt_count: number;
    remaining_attempts: number;
    expires_at: string;
    consumed_at: string | null;
    created_at: string;
};
