// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthConfigurationVO } from "./AuthConfigurationVO";
import type { RegistrationConfigurationVO } from "./RegistrationConfigurationVO";

export type ApplicationConfigurationVO = {
    auth: AuthConfigurationVO;
    registration: RegistrationConfigurationVO;
};
