// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Argon2Configuration } from "./Argon2Configuration";
import type { AuthenticationConfigurationVO } from "./AuthenticationConfigurationVO";

export type ApplicationConfigurationVO = {
    authentication: AuthenticationConfigurationVO;
    enable_registration: boolean;
    argon2: Argon2Configuration;
};
