// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdministratorVO } from "./AdministratorVO";

export type CreateAdministratorResponse = {
    administrator: AdministratorVO;
    initial_password: string;
};
