// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateApplicationUserRequest = { 
/**
 * User email address (optional, but either phone or email must be provided)
 */
email: string | null, 
/**
 * User phone number (optional, but either phone or email must be provided)
 */
phone: string | null, 
/**
 * User nickname (optional, if not provided, two random words will be generated)
 */
nickname: string, password: string, };
