// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyAlg } from "./KeyAlg";
import type { KeyStatus } from "./KeyStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type KeyBoxes = {
    id: string;
    key_alg: KeyAlg;
    status: KeyStatus;
    created_at: string;
    activated_at: string | null;
    retired_at: string | null;
    revoked_at: string | null;
    expires_at: string | null;
    secret: JsonValue;
    application_id: string;
};
