// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchTokenConfigurationVO } from "./PatchTokenConfigurationVO";
import type { PatchTotpConfigurationVO } from "./PatchTotpConfigurationVO";

export type PatchAuthConfigurationVO = {
    token: PatchTokenConfigurationVO | null;
    totp: PatchTotpConfigurationVO | null;
};
