// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchAuthenticationConfigurationVO } from "./PatchAuthenticationConfigurationVO";

export type PatchApplicationConfigurationRequest = {
    authentication: PatchAuthenticationConfigurationVO | null;
    enable_registration: boolean | null;
};
