// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sqid } from "./Sqid";

export type SecretVO = {
    id: Sqid;
    secret: string;
    created_at: string;
    revoked_at: string | null;
    application_ids: Array<Sqid>;
};
