// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigninChallenge } from "./SigninChallenge";
import type { SignupResponse } from "./SignupResponse";

export type SigninResponseSchema = SignupResponse | SigninChallenge;
