// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubjectTypeEnum } from "./SubjectTypeEnum";

export type Subjects = {
    id: string;
    type: SubjectTypeEnum;
    application_id: string;
    created_at: string;
};
