// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an authentication token should be delivered back to the client.
 *
 * This is typically chosen by the endpoint that issues or refreshes tokens.
 *
 * The dispatch method can be controlled by the request header
 * `X-OceanIAM-Token-Dispatch`.
 *
 * - Accepted values: `cookie`, `json`, `both` (case-insensitive; whitespace is ignored)
 * - Default: missing/invalid header falls back to `both`
 *
 * Common use-cases:
 * - Browser apps often prefer `Cookie` so the token is automatically attached
 *   to subsequent requests (and can be protected with `HttpOnly`, `Secure`,
 *   `SameSite`, etc.).
 * - API clients (mobile/desktop/CLI/SDK) often prefer `Json` so they can
 *   manage the token explicitly (e.g., attach it as an `Authorization: Bearer`
 *   header).
 * - During migrations or when you need to support both kinds of clients,
 *   `Both` can be used to send the token in both places.
 */
export type TokenDispatchMethod = "Cookie" | "Json" | "Both";
