// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Users = {
    id: string;
    application_id: string;
    email: string | null;
    phone: string | null;
    nickname: string;
};
