use std::marker::PhantomData;

use axum::{
    extract::FromRequestParts,
    http::{request::Parts, StatusCode},
};
use oceaniam_common::sqid::Sqid;
use oceaniam_permission::Permission;
use tracing::error;
use uuid::Uuid;

use crate::{error::Error, middlewares::auth::ApplicationAuthGuard, state::AppState};

/// Marker trait for application-level permissions.
///
/// Each permission constant is generated by the [`app_perm`] macro.
pub trait AppPermission {
    const PERMISSION: Permission;
}

macro_rules! app_perm {
    ($name:ident => $perm:expr) => {
        #[allow(missing_docs)]
        pub struct $name;
        impl AppPermission for $name {
            const PERMISSION: Permission = $perm;
        }
    };
}

app_perm!(AppUserRead => Permission::ApplicationUserRead);
app_perm!(AppUserInvite => Permission::ApplicationUserInvite);
app_perm!(AppUserPatch => Permission::ApplicationUserPatch);
app_perm!(AppUserDelete => Permission::ApplicationUserDelete);
app_perm!(AppTokenIssue => Permission::ApplicationTokenIssue);
app_perm!(AppTokenRevoke => Permission::ApplicationTokenRevoke);
app_perm!(AppChallengeRead => Permission::ApplicationChallengeRead);

/// Application-level permission guard.
///
/// Combines JWT authentication (`ApplicationAuthGuard`) with a permission
/// check against the resolved subject-level permission set.
pub struct AppPermissionGuard<P: AppPermission> {
    pub subject_id: Uuid,
    pub application_id: Uuid,
    _permission: PhantomData<P>,
}

impl<P: AppPermission> FromRequestParts<AppState<'_>> for AppPermissionGuard<P> {
    type Rejection = Error;

    async fn from_request_parts(
        parts: &mut Parts,
        state: &AppState<'_>,
    ) -> Result<Self, Self::Rejection> {
        let auth = ApplicationAuthGuard::from_request_parts(parts, state)
            .await
            .map_err(|code| {
                error!(?code, "authentication failed in app permission guard");
                Error::with_code(code, "authentication failed")
            })?;

        let subject_id = auth.token.claims.sub;

        let path_segments: Vec<&str> = parts.uri.path().split('/').collect();
        let application_id = path_segments
            .iter()
            .position(|&segment| segment == "applications")
            .and_then(|idx| path_segments.get(idx + 1))
            .and_then(|id| id.parse::<Sqid>().ok())
            .and_then(|id| Uuid::try_from(id).ok())
            .ok_or_else(|| {
                error!("failed to parse application_id from path in app permission guard");
                Error::with_code(StatusCode::BAD_REQUEST, "invalid application_id")
            })?;

        let perms = state
            .platform_permissions
            .subject_permissions(subject_id, application_id)
            .await
            .map_err(|e| {
                error!(
                    %subject_id,
                    %application_id,
                    error = %e,
                    "subject permission resolution failed"
                );
                Error::with_code(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "subject permission resolution failed",
                )
            })?;

        if !perms.contains(&P::PERMISSION) {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN,
                "insufficient permissions",
            ));
        }

        Ok(Self {
            subject_id,
            application_id,
            _permission: PhantomData,
        })
    }
}
