use std::marker::PhantomData;

use axum::{
    extract::FromRequestParts,
    http::{StatusCode, request::Parts},
};
use oceaniam_permission::Permission;
use tracing::error;
use uuid::Uuid;

use crate::{error::Error, middlewares::auth::ApplicationAuthGuard, state::AppState};

/// Marker trait for application-level permissions.
///
/// Each permission constant is generated by the [`app_perm`] macro.
///
/// NOTE: intentionally not unified with [`super::permission`]. The two
/// guards differ beyond auth extraction — resolver method and context,
/// resolution-failure logging/messages, and returned identity fields — so a
/// generic `PermissionGuard` would need a broader policy seam. Keep the twin
/// implementations until that seam is designed.
pub trait AppPermission {
    const PERMISSION: Permission;
}

macro_rules! app_perm {
    ($name:ident => $perm:expr) => {
        #[allow(missing_docs)]
        pub struct $name;
        impl AppPermission for $name {
            const PERMISSION: Permission = $perm;
        }
    };
}

// These markers, and the current use of `AppUserRead` by role mutations, are intentionally
// reserved for upcoming application-scoped ORBAC wiring; keep them until that work lands.
app_perm!(AppUserRead => Permission::ApplicationUserRead);
app_perm!(AppUserInvite => Permission::ApplicationUserInvite);
app_perm!(AppUserPatch => Permission::ApplicationUserPatch);
app_perm!(AppUserDelete => Permission::ApplicationUserDelete);
app_perm!(AppTokenIssue => Permission::ApplicationTokenIssue);
app_perm!(AppTokenRevoke => Permission::ApplicationTokenRevoke);
app_perm!(AppChallengeRead => Permission::ApplicationChallengeRead);

/// Application-level permission guard.
///
/// Combines JWT authentication (`ApplicationAuthGuard`) with a permission
/// check against the resolved subject-level permission set.
pub struct AppPermissionGuard<P: AppPermission> {
    pub subject_id: Uuid,
    pub application_id: Uuid,
    _permission: PhantomData<P>,
}

impl<P: AppPermission> FromRequestParts<AppState> for AppPermissionGuard<P> {
    type Rejection = Error;

    async fn from_request_parts(
        parts: &mut Parts,
        state: &AppState,
    ) -> Result<Self, Self::Rejection> {
        let auth = ApplicationAuthGuard::from_request_parts(parts, state)
            .await
            .map_err(|code| {
                error!(?code, "authentication failed in app permission guard");
                Error::with_code(code, "authentication failed")
            })?;

        let subject_id = auth.subject_id;
        let application_id = auth.application_id;

        let perms = state
            .platform_permissions
            .subject_permissions(subject_id, application_id)
            .await
            .map_err(|e| {
                error!(
                    %subject_id,
                    %application_id,
                    error = %e,
                    "subject permission resolution failed"
                );
                Error::with_code(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "subject permission resolution failed",
                )
            })?;

        if !perms.contains(&P::PERMISSION) {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN,
                "insufficient permissions",
            ));
        }

        Ok(Self {
            subject_id,
            application_id,
            _permission: PhantomData,
        })
    }
}
