use axum::{
    extract::FromRequestParts,
    http::{StatusCode, request::Parts},
};
use oceaniam_auth::jwt::SystemClaim;
use oceaniam_common::consts;
use oceaniam_database::model::prelude::{AdministratorTenants, Administrators};
use oceaniam_permission::{Permission, PlatformRole};
use sea_orm::{ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter};
use tracing::error;
use uuid::Uuid;

use crate::error::Error;
use crate::middlewares::auth::PlatformAuthGuard;
use crate::state::AppState;

/// Marker trait for platform-level permissions.
///
/// Each permission constant is generated by the [`platform_perm`] macro.
pub trait PlatformPermission {
    const PERMISSION: Permission;
}

macro_rules! platform_perm {
    ($name:ident => $perm:expr) => {
        #[allow(missing_docs)]
        pub struct $name;
        impl PlatformPermission for $name {
            const PERMISSION: Permission = $perm;
        }
    };
}

platform_perm!(TenantRead => Permission::TenantRead);
platform_perm!(TenantCreate => Permission::TenantCreate);
platform_perm!(TenantPatch => Permission::TenantPatch);
platform_perm!(TenantDelete => Permission::TenantDelete);
platform_perm!(ApplicationRead => Permission::ApplicationRead);
platform_perm!(ApplicationCreate => Permission::ApplicationCreate);
platform_perm!(ApplicationPatch => Permission::ApplicationPatch);
platform_perm!(ApplicationDelete => Permission::ApplicationDelete);
platform_perm!(ApplicationConfigurationRead => Permission::ApplicationConfigurationRead);
platform_perm!(ApplicationConfigurationPatch => Permission::ApplicationConfigurationPatch);
platform_perm!(OidcClientRead => Permission::OidcClientRead);
platform_perm!(OidcClientCreate => Permission::OidcClientCreate);
platform_perm!(OidcClientPatch => Permission::OidcClientPatch);
platform_perm!(OidcClientDelete => Permission::OidcClientDelete);
platform_perm!(SecretRead => Permission::SecretRead);
platform_perm!(SecretCreate => Permission::SecretCreate);
platform_perm!(SecretDelete => Permission::SecretDelete);
platform_perm!(KeyRead => Permission::KeyRead);
platform_perm!(KeyRotate => Permission::KeyRotate);
platform_perm!(KeyRevoke => Permission::KeyRevoke);
platform_perm!(AdministratorRead => Permission::AdministratorRead);
platform_perm!(AdministratorCreate => Permission::AdministratorCreate);
platform_perm!(AdministratorPatch => Permission::AdministratorPatch);

/// Platform-level permission guard.
///
/// Combines JWT authentication (`RequireAuth<SystemClaim>`) with a permission
/// check against the resolved permission set for the authenticated administrator.
///
/// # Example
///
/// ```ignore
/// use crate::middlewares::permission::{PlatformPermissionGuard, TenantRead};
///
/// async fn list_tenants(
///     _: PlatformPermissionGuard<TenantRead>,
/// ) -> RestResult<...> {
///     // ...
/// }
/// ```
pub struct PlatformPermissionGuard<P: PlatformPermission> {
    pub claim: SystemClaim,
    _permission: std::marker::PhantomData<P>,
}

impl<P: PlatformPermission> PlatformPermissionGuard<P> {
    /// Enforce the tenant organization boundary after the activity permission has been resolved.
    ///
    /// Super administrators can access every tenant. Readonly administrators are platform-wide
    /// observers. Tenant administrators must have an explicit `administrator_tenants` assignment.
    pub async fn ensure_tenant_scope(
        &self,
        tenant_id: Uuid,
        database: &DatabaseConnection,
    ) -> Result<(), Error> {
        let operator_id = self.claim.sub;
        if operator_id == consts::SYSTEM_APPLICATION_UUID {
            return Ok(());
        }

        let administrator = Administrators::find_by_id(operator_id)
            .one(database)
            .await?
            .ok_or_else(|| {
                Error::with_code(StatusCode::FORBIDDEN, "administrator is not available")
            })?;
        let role = administrator
            .role
            .as_deref()
            .and_then(|role| role.parse::<PlatformRole>().ok())
            .ok_or_else(|| {
                Error::with_code(StatusCode::FORBIDDEN, "administrator role is invalid")
            })?;

        // The permission resolver is cached. Recheck the freshly loaded role before combining its
        // scope with a cached activity set, otherwise a TenantAdmin -> ReadonlyAdmin transition
        // could temporarily retain write permission while gaining global read scope.
        if !role.permissions().contains(&P::PERMISSION) {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN,
                "insufficient permissions",
            ));
        }

        if matches!(role, PlatformRole::SuperAdmin | PlatformRole::ReadonlyAdmin) {
            return Ok(());
        }

        use oceaniam_database::model::administrator_tenants::Column::*;
        let assigned = AdministratorTenants::find()
            .filter(AdministratorId.eq(operator_id))
            .filter(TenantId.eq(tenant_id))
            .one(database)
            .await?
            .is_some();

        if !assigned {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN,
                "insufficient tenant scope",
            ));
        }

        Ok(())
    }
}

impl<P: PlatformPermission> FromRequestParts<AppState> for PlatformPermissionGuard<P> {
    type Rejection = Error;

    async fn from_request_parts(
        parts: &mut Parts,
        state: &AppState,
    ) -> Result<Self, Self::Rejection> {
        let PlatformAuthGuard { token } = PlatformAuthGuard::from_request_parts(parts, state)
            .await
            .map_err(|code| {
                error!(?code, "authentication failed in permission guard");
                Error::with_code(code, "authentication failed")
            })?;

        let platform_id = token.claims.sub;

        let perms = state
            .platform_permissions
            .platform_permissions(platform_id)
            .await
            .map_err(|e| {
                error!(%platform_id, error = %e, "permission resolution failed");
                Error::with_code(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "permission resolution failed",
                )
            })?;

        if !perms.contains(&P::PERMISSION) {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN,
                "insufficient permissions",
            ));
        }

        Ok(Self {
            claim: token.claims,
            _permission: std::marker::PhantomData,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // NOTE: AI-generated test
    #[test]
    fn oidc_client_markers_reference_their_matching_permissions() {
        assert_eq!(OidcClientRead::PERMISSION, Permission::OidcClientRead);
        assert_eq!(OidcClientCreate::PERMISSION, Permission::OidcClientCreate);
        assert_eq!(OidcClientPatch::PERMISSION, Permission::OidcClientPatch);
        assert_eq!(OidcClientDelete::PERMISSION, Permission::OidcClientDelete);
    }
}
