use axum::{
    extract::FromRequestParts,
    http::{StatusCode, request::Parts},
};
use oceaniam_auth::jwt::SystemClaim;
use oceaniam_permission::Permission;
use tracing::error;

use crate::error::Error;
use crate::middlewares::auth::RequireAuthGuard;
use crate::state::AppState;

/// Marker trait for platform-level permissions.
///
/// Each permission constant is generated by the [`platform_perm`] macro.
pub trait PlatformPermission {
    const PERMISSION: Permission;
}

macro_rules! platform_perm {
    ($name:ident => $perm:expr) => {
        #[allow(missing_docs)]
        pub struct $name;
        impl PlatformPermission for $name {
            const PERMISSION: Permission = $perm;
        }
    };
}

platform_perm!(TenantRead => Permission::TenantRead);
platform_perm!(TenantCreate => Permission::TenantCreate);
platform_perm!(TenantPatch => Permission::TenantPatch);
platform_perm!(TenantDelete => Permission::TenantDelete);
platform_perm!(ApplicationRead => Permission::ApplicationRead);
platform_perm!(ApplicationCreate => Permission::ApplicationCreate);
platform_perm!(ApplicationPatch => Permission::ApplicationPatch);
platform_perm!(ApplicationDelete => Permission::ApplicationDelete);
platform_perm!(ApplicationConfigurationRead => Permission::ApplicationConfigurationRead);
platform_perm!(ApplicationConfigurationPatch => Permission::ApplicationConfigurationPatch);
platform_perm!(SecretRead => Permission::SecretRead);
platform_perm!(SecretCreate => Permission::SecretCreate);
platform_perm!(SecretDelete => Permission::SecretDelete);
platform_perm!(KeyRead => Permission::KeyRead);
platform_perm!(KeyRotate => Permission::KeyRotate);
platform_perm!(KeyRevoke => Permission::KeyRevoke);
platform_perm!(AdministratorRead => Permission::AdministratorRead);
platform_perm!(AdministratorCreate => Permission::AdministratorCreate);
platform_perm!(AdministratorPatch => Permission::AdministratorPatch);

/// Platform-level permission guard.
///
/// Combines JWT authentication (`RequireAuth<SystemClaim>`) with a permission
/// check against the resolved permission set for the authenticated administrator.
///
/// # Example
///
/// ```ignore
/// use crate::middlewares::permission::{RequirePlatformPermission, TenantRead};
///
/// async fn list_tenants(
///     _: RequirePlatformPermission<TenantRead>,
/// ) -> RestResult<...> {
///     // ...
/// }
/// ```
pub struct RequirePlatformPermission<P: PlatformPermission> {
    pub claim: SystemClaim,
    _permission: std::marker::PhantomData<P>,
}

impl<P: PlatformPermission> FromRequestParts<AppState<'_>> for RequirePlatformPermission<P> {
    type Rejection = Error;

    async fn from_request_parts(
        parts: &mut Parts,
        state: &AppState<'_>,
    ) -> Result<Self, Self::Rejection> {
        let RequireAuthGuard { token } =
            RequireAuthGuard::<SystemClaim>::from_request_parts(parts, state)
                .await
                .map_err(|code| {
                    error!(?code, "authentication failed in permission guard");
                    Error::with_code(code.as_u16(), "authentication failed")
                })?;

        let platform_id = token.claims.sub;

        let perms = state
            .system_permissions
            .platform_permissions(platform_id)
            .await
            .map_err(|e| {
                error!(%platform_id, error = %e, "permission resolution failed");
                Error::with_code(
                    StatusCode::INTERNAL_SERVER_ERROR.as_u16(),
                    "permission resolution failed",
                )
            })?;

        if !perms.contains(&P::PERMISSION) {
            return Err(Error::with_code(
                StatusCode::FORBIDDEN.as_u16(),
                "insufficient permissions",
            ));
        }

        Ok(Self {
            claim: token.claims,
            _permission: std::marker::PhantomData,
        })
    }
}
