[package]
name = "oceaniam-vo"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
garde.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
utoipa.workspace = true
uuid = { workspace = true, features = ["serde"] }
