[package]
name = "oceaniam"
version.workspace = true
edition.workspace = true

[dependencies]
argon2.workspace = true
async-trait.workspace = true
axum-extra.workspace = true
axum-valid.workspace = true
axum.workspace = true
backon.workspace = true
chrono.workspace = true
config.workspace = true
crossbeam-queue.workspace = true
dotenvy.workspace = true
futures.workspace = true
im.workspace = true
itertools.workspace = true
jsonwebtoken.workspace = true
log.workspace = true
mimalloc.workspace = true
moka.workspace = true
parking_lot.workspace = true
rapidhash.workspace = true
rayon.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
utoipa-axum.workspace = true
utoipa-scalar.workspace = true
utoipa.workspace = true
uuid.workspace = true
xorf.workspace = true

oceaniam-api.workspace = true
oceaniam-audit.workspace = true
oceaniam-auth.workspace = true
oceaniam-common.workspace = true
oceaniam-credential.workspace = true
oceaniam-database.workspace = true
oceaniam-keybox.workspace = true
oceaniam-vo = { workspace = true, features = ["database"] }

[dev-dependencies]
reqwest.workspace = true
migration.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
rand.workspace = true
