//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "application_secret_bindings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub secret_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub application_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::application_secrets::Entity",
        from = "Column::SecretId",
        to = "super::application_secrets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApplicationSecrets,
    #[sea_orm(
        belongs_to = "super::applications::Entity",
        from = "Column::ApplicationId",
        to = "super::applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Applications,
}

impl Related<super::application_secrets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationSecrets.def()
    }
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
