//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "application_secrets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub secret: String,
    pub created_at: DateTimeWithTimeZone,
    pub revoked_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application_secret_bindings::Entity")]
    ApplicationSecretBindings,
}

impl Related<super::application_secret_bindings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationSecretBindings.def()
    }
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        super::application_secret_bindings::Relation::Applications.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::application_secret_bindings::Relation::ApplicationSecrets
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
