//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "applications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub comment: Option<String>,
    pub tenant_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub configuration: Json,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application_roles::Entity")]
    ApplicationRoles,
    #[sea_orm(has_many = "super::application_secret_bindings::Entity")]
    ApplicationSecretBindings,
    #[sea_orm(has_many = "super::subjects::Entity")]
    Subjects,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tenants,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::application_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationRoles.def()
    }
}

impl Related<super::application_secret_bindings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationSecretBindings.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::application_secrets::Entity> for Entity {
    fn to() -> RelationDef {
        super::application_secret_bindings::Relation::ApplicationSecrets.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::application_secret_bindings::Relation::Applications
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
