//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oidc_client_redirect_uris")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_oidc_client_redirect_uris_client_uri")]
    pub oidc_client_id: Uuid,
    #[sea_orm(unique_key = "uq_oidc_client_redirect_uris_client_uri")]
    pub redirect_uri: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::oidc_clients::Entity",
        from = "Column::OidcClientId",
        to = "super::oidc_clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OidcClients,
}

impl Related<super::oidc_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcClients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
