//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::OidcAuthorizationTransactionStatus;
use super::sea_orm_active_enums::OidcPkceMethod;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oidc_authorization_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub application_id: Uuid,
    pub oidc_client_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub issuer: String,
    pub redirect_uri: String,
    pub requested_scope: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub nonce: Option<String>,
    pub code_challenge: String,
    pub code_challenge_method: OidcPkceMethod,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub browser_binding_digest: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub csrf_digest: Vec<u8>,
    pub status: OidcAuthorizationTransactionStatus,
    pub revision: i64,
    pub terminal_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub subject_id: Option<Uuid>,
    pub authenticated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::applications::Entity",
        from = "(Column::TenantId, Column::ApplicationId)",
        to = "(super::applications::Column::TenantId, super::applications::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Applications,
    #[sea_orm(
        belongs_to = "super::oidc_clients::Entity",
        from = "(Column::ApplicationId, Column::OidcClientId)",
        to = "(super::oidc_clients::Column::ApplicationId, super::oidc_clients::Column::Id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OidcClients,
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subjects,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tenants,
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl Related<super::oidc_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcClients.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
