//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::OidcApplicationType;
use super::sea_orm_active_enums::OidcClientType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oidc_clients")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "uq_oidc_clients_application_id_id_auth_tx"
    )]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_oidc_clients_application_id_id_auth_tx")]
    pub application_id: Uuid,
    #[sea_orm(unique)]
    pub client_id: String,
    pub name: String,
    pub client_type: OidcClientType,
    pub application_type: OidcApplicationType,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::applications::Entity",
        from = "Column::ApplicationId",
        to = "super::applications::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Applications,
    #[sea_orm(has_many = "super::oidc_authorization_transactions::Entity")]
    OidcAuthorizationTransactions,
    #[sea_orm(has_many = "super::oidc_client_redirect_uris::Entity")]
    OidcClientRedirectUris,
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl Related<super::oidc_authorization_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcAuthorizationTransactions.def()
    }
}

impl Related<super::oidc_client_redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OidcClientRedirectUris.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
