//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::administrator_tenants::Entity as AdministratorTenants;
pub use super::administrators::Entity as Administrators;
pub use super::application_roles::Entity as ApplicationRoles;
pub use super::application_secret_bindings::Entity as ApplicationSecretBindings;
pub use super::application_secrets::Entity as ApplicationSecrets;
pub use super::application_summary::Entity as ApplicationSummary;
pub use super::applications::Entity as Applications;
pub use super::audit_summary_by_application::Entity as AuditSummaryByApplication;
pub use super::audits::Entity as Audits;
pub use super::challenges::Entity as Challenges;
pub use super::credentials::Entity as Credentials;
pub use super::key_boxes::Entity as KeyBoxes;
pub use super::platform_summary::Entity as PlatformSummary;
pub use super::revoked_jwts::Entity as RevokedJwts;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::subject_roles::Entity as SubjectRoles;
pub use super::subjects::Entity as Subjects;
pub use super::tenants::Entity as Tenants;
pub use super::users::Entity as Users;
