//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "role_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::application_roles::Entity",
        from = "Column::RoleId",
        to = "super::application_roles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApplicationRoles,
}

impl Related<super::application_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
