//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    ts_rs :: TS,
    strum :: Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "key_alg")]
pub enum KeyAlg {
    #[sea_orm(string_value = "rs256")]
    Rs256,
    #[sea_orm(string_value = "rs384")]
    Rs384,
    #[sea_orm(string_value = "rs512")]
    Rs512,
    #[sea_orm(string_value = "ps256")]
    Ps256,
    #[sea_orm(string_value = "ps384")]
    Ps384,
    #[sea_orm(string_value = "ps512")]
    Ps512,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    ts_rs :: TS,
    strum :: Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "key_status")]
pub enum KeyStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "retired")]
    Retired,
    #[sea_orm(string_value = "revoked")]
    Revoked,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    ts_rs :: TS,
    strum :: Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "subject_type_enum")]
pub enum SubjectTypeEnum {
    #[sea_orm(string_value = "user")]
    User,
}
