//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "audit_type")]
pub enum AuditType {
    #[sea_orm(string_value = "sign_jwt")]
    SignJwt,
    #[sea_orm(string_value = "revoke_jwt")]
    RevokeJwt,
    #[sea_orm(string_value = "create_application")]
    CreateApplication,
    #[sea_orm(string_value = "delete_application")]
    DeleteApplication,
    #[sea_orm(string_value = "create_tenants")]
    CreateTenants,
    #[sea_orm(string_value = "delete_tenants")]
    DeleteTenants,
    #[sea_orm(string_value = "create_application_user")]
    CreateApplicationUser,
    #[sea_orm(string_value = "delete_application_user")]
    DeleteApplicationUser,
    #[sea_orm(string_value = "create_application_secret")]
    CreateApplicationSecret,
    #[sea_orm(string_value = "delete_application_secret")]
    DeleteApplicationSecret,
    #[sea_orm(string_value = "refresh_jwt")]
    RefreshJwt,
    #[sea_orm(string_value = "patch_application_configuration")]
    PatchApplicationConfiguration,
    #[sea_orm(string_value = "patch_application")]
    PatchApplication,
    #[sea_orm(string_value = "patch_tenant")]
    PatchTenant,
    #[sea_orm(string_value = "create_administrator")]
    CreateAdministrator,
    #[sea_orm(string_value = "patch_administrator")]
    PatchAdministrator,
    #[sea_orm(string_value = "create_challenge")]
    CreateChallenge,
    #[sea_orm(string_value = "verify_challenge")]
    VerifyChallenge,
    #[sea_orm(string_value = "rotate_key")]
    RotateKey,
    #[sea_orm(string_value = "revoke_key")]
    RevokeKey,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "challenge_factor_type"
)]
pub enum ChallengeFactorType {
    #[sea_orm(string_value = "totp")]
    Totp,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "challenge_purpose_type"
)]
pub enum ChallengePurposeType {
    #[sea_orm(string_value = "signin")]
    Signin,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "challenge_status_type"
)]
pub enum ChallengeStatusType {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "consumed")]
    Consumed,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "key_alg")]
pub enum KeyAlg {
    #[sea_orm(string_value = "rs256")]
    Rs256,
    #[sea_orm(string_value = "rs384")]
    Rs384,
    #[sea_orm(string_value = "rs512")]
    Rs512,
    #[sea_orm(string_value = "ps256")]
    Ps256,
    #[sea_orm(string_value = "ps384")]
    Ps384,
    #[sea_orm(string_value = "ps512")]
    Ps512,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "key_status")]
pub enum KeyStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "retired")]
    Retired,
    #[sea_orm(string_value = "revoked")]
    Revoked,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "subject_type_enum")]
pub enum SubjectTypeEnum {
    #[sea_orm(string_value = "user")]
    User,
}
