//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub comment: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::administrator_tenants::Entity")]
    AdministratorTenants,
    #[sea_orm(has_many = "super::applications::Entity")]
    Applications,
    #[sea_orm(has_many = "super::key_boxes::Entity")]
    KeyBoxes,
}

impl Related<super::administrator_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdministratorTenants.def()
    }
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl Related<super::key_boxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeyBoxes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
